services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nodejs-app:latest

    container_name: node-web
    restart: always
    ports:
      - "8081:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017

  db:
    image: mongo:latest
    container_name: node-mongo-db
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
